layers:
  - Input:
      shape: in_shape
  - Conv2D:
      filters: 64
      kernel_size: [7, 7]
      padding: same
      use_bias: false
      name: conv_1_1
  - BatchNormalization:
  - Activation:
      activation: relu
  - Conv2D:
      filters: 64
      kernel_size: [7, 7]
      padding: same
      use_bias: false
      name: conv_1_2
  - BatchNormalization:
  - Activation:
      activation: relu
  - MaxPooling2D:
      pool_size: [2, 2]
      strides: 2
      name: pooling_1
  - UpSampling2D:
      size: [2, 2]
      name: upsampling_5
  - Conv2DTranspose:
      filters: 64
      kernel_size: [7, 7]
      strides: [1, 1]
      padding: same
      name: conv_T_5_1
  - BatchNormalization:
  - Activation:
      activation: relu
  - Conv2DTranspose:
      filters: 64
      kernel_size: [7, 7]
      strides: [1, 1]
      padding: same
      name: conv_T_5_2
  - BatchNormalization:
  - Activation:
      activation: relu
  - Conv2D:
      filters: num_bands
      kernel_size: [7, 7]
      activation: relu
      padding: same
