# Linting and testing on commit
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: DELTA Continuous Integration

on:
  push:
    branches: [ 'master', 'develop' ]
  pull_request:
    branches: [ 'master', 'develop' ]

jobs:
  continuous_integration:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install DELTA
      run: |
        ./scripts/setup.sh
        python3 -m pip install pylint pytest
        python3 -m pip install .
    - name: Lint with pylint
      run: |
        find . -type f -name "*.py" | xargs --null --no-run-if-empty ./scripts/linter/lint
    - name: Test with pytest
      run: |
        pytest tests

